# Generated by Django 2.2.7 on 2019-11-05 03:31

from django.db import migrations
import imagekit.models.fields
import leafsheets_django.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191104_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=leafsheets_django.utils.PathAndRename('users/avatars/')),
        ),
    ]
