# Generated by Django 2.2.6 on 2019-11-04 21:39

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(max_length=250)),
                ('download_title', models.CharField(blank=True, max_length=250, null=True)),
                ('short_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('use_case', models.CharField(blank=True, max_length=50, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('bullets', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), default=list, size=None)),
                ('hours_saved', models.IntegerField(blank=True, null=True)),
                ('traditional_cost', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'sheet',
                'verbose_name_plural': 'sheets',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('type_of_inc', models.CharField(max_length=4)),
                ('country', models.CharField(max_length=4)),
                ('category', models.CharField(choices=[('M', 'Medical'), ('R', 'Recreational'), ('B', 'Both')], max_length=4)),
                ('new_status', models.CharField(choices=[('N', 'New'), ('O', 'Old')], max_length=1)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
