# Generated by Django 2.2.7 on 2019-11-04 22:54

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0002_auto_20191104_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='address.Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='type_of_inc',
            field=models.CharField(choices=[('C', 'C Corp'), ('S', 'S Corp'), ('LLC', 'Limited Liability Corp'), ('DBA', 'Doing Business As')], max_length=4),
        ),
    ]
