# Generated by Django 2.2.7 on 2019-11-04 23:57

from django.db import migrations, models
import leafsheets_django.utils


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0003_auto_20191104_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=leafsheets_django.utils.PathAndRename('/sheets/icons')),
        ),
    ]
