# Generated by Django 2.2.7 on 2019-11-05 03:31

from django.db import migrations, models
import leafsheets_django.utils


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0004_sheet_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=leafsheets_django.utils.PathAndRename('sheets/icons/')),
        ),
    ]
