# Generated by Django 2.2.7 on 2019-11-05 05:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0005_auto_20191105_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='bullets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
