# Generated by Django 2.2.7 on 2019-11-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0007_auto_20191105_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='updated_at',
            field=models.DateTimeField(editable=False),
        ),
    ]
