# Generated by Django 2.2.7 on 2019-11-05 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leafsheets', '0008_auto_20191105_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('udpated_at', models.DateTimeField()),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sheets', to='leafsheets.Sheet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Sheet',
                'verbose_name_plural': 'User Sheets',
            },
        ),
    ]
