# Generated by Django 2.2.7 on 2019-11-05 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0009_usersheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersheet',
            old_name='udpated_at',
            new_name='updated_at',
        ),
    ]
