# Generated by Django 2.2.7 on 2019-11-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0011_sheet_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='use_case',
            field=models.CharField(blank=True, choices=[('P', 'Production'), ('C', 'Cultivation'), ('D', 'Dispensary')], max_length=50, null=True),
        ),
    ]
