# Generated by Django 2.2.7 on 2019-11-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0012_auto_20191106_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
