# Generated by Django 2.2.7 on 2019-11-17 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0014_auto_20191112_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
    ]
