# Generated by Django 2.2.8 on 2019-12-11 01:48

from django.db import migrations, models
import leafsheets_django.utils


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0015_remove_company_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('title', models.CharField(max_length=250)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('doc', models.FileField(upload_to=leafsheets_django.utils.PathAndRename('documents/docs/'))),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
