# Generated by Django 2.2.8 on 2020-01-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0016_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='use_case',
            field=models.CharField(choices=[('P', 'Production'), ('C', 'Cultivation'), ('D', 'Dispensary'), ('M', 'Multiple Purposes')], default='M', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='new_status',
            field=models.CharField(choices=[('N', 'New'), ('E', 'Existing')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='use_case',
            field=models.CharField(blank=True, choices=[('P', 'Production'), ('C', 'Cultivation'), ('D', 'Dispensary'), ('M', 'Multiple Purposes')], max_length=50, null=True),
        ),
    ]
