# Generated by Django 2.2.8 on 2020-01-28 23:25

from django.db import migrations
import imagekit.models.fields
import leafsheets_django.utils


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0018_company_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='icon',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=leafsheets_django.utils.PathAndRename('companies/icons/')),
        ),
    ]
