# Generated by Django 2.2.8 on 2020-02-24 18:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0020_auto_20200214_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersheet',
            name='user_variable_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
