# Generated by Django 2.2.8 on 2020-03-02 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0021_usersheet_user_variable_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='sheet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc', to='leafsheets.Sheet'),
        ),
    ]
