# Generated by Django 2.2.8 on 2020-03-05 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0022_auto_20200302_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet', to='commerce.Item'),
        ),
    ]
