# Generated by Django 2.2.8 on 2020-03-05 19:13

from django.db import migrations, models
import leafsheets_django.utils


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0023_auto_20200305_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='template_doc',
            field=models.FileField(blank=True, null=True, upload_to=leafsheets_django.utils.PathAndRename('documents/docs/templates/')),
        ),
    ]
