# Generated by Django 2.2.8 on 2020-03-08 04:14

from django.db import migrations, models
import leafsheets_django.storage_backends
import leafsheets_django.utils


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0024_auto_20200305_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersheet',
            name='user_variable_doc',
            field=models.FileField(blank=True, null=True, storage=leafsheets_django.storage_backends.PrivateMediaStorage(), upload_to=leafsheets_django.utils.PathAndRename('documents/docs/variable/')),
        ),
        migrations.AlterField(
            model_name='document',
            name='template_doc',
            field=models.FileField(blank=True, null=True, storage=leafsheets_django.storage_backends.PrivateMediaStorage(), upload_to=leafsheets_django.utils.PathAndRename('documents/docs/templates/')),
        ),
        migrations.AlterField(
            model_name='document',
            name='variable_doc',
            field=models.FileField(blank=True, null=True, storage=leafsheets_django.storage_backends.PrivateMediaStorage(), upload_to=leafsheets_django.utils.PathAndRename('documents/docs/variable/')),
        ),
    ]
