# Generated by Django 2.2.8 on 2020-03-08 07:15

from django.db import migrations, models
import leafsheets.models
import leafsheets_django.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0025_auto_20200308_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersheet',
            name='user_variable_doc',
            field=models.FileField(blank=True, null=True, storage=leafsheets_django.storage_backends.PrivateMediaStorage(), upload_to=leafsheets.models.user_variable_doc_path),
        ),
    ]
