# Generated by Django 2.2.8 on 2020-03-17 18:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0026_auto_20200308_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='toc',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
