# Generated by Django 2.2.8 on 2020-03-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0027_sheet_toc'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersheet',
            name='completed_input_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usersheet',
            name='total_input_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usersheet',
            name='total_variable_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
