# Generated by Django 2.2.8 on 2020-03-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0028_auto_20200317_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersheet',
            old_name='total_variable_count',
            new_name='var_count',
        ),
        migrations.AddField(
            model_name='usersheet',
            name='required_input_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
