# Generated by Django 2.2.8 on 2020-05-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0029_auto_20200317_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersheet',
            name='completed_required_input_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
