# Generated by Django 2.2.8 on 2020-05-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0030_usersheet_completed_required_input_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersheet',
            name='user_variable_pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
