# Generated by Django 2.2.8 on 2020-05-13 01:06

from django.db import migrations, models
import leafsheets.models
import leafsheets_django.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0031_usersheet_user_variable_pdf_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersheet',
            name='user_variable_pdf_url',
        ),
        migrations.AddField(
            model_name='usersheet',
            name='user_variable_pdf',
            field=models.FileField(blank=True, null=True, storage=leafsheets_django.storage_backends.PrivateMediaStorage(), upload_to=leafsheets.models.user_variable_pdf_path),
        ),
    ]
