# Generated by Django 2.2.8 on 2020-05-21 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0032_auto_20200513_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='toc',
        ),
    ]
