# Generated by Django 2.2.8 on 2020-05-21 21:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leafsheets', '0034_remove_sheet_toc'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='toc',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None), default=list, size=None),
        ),
    ]
