FROM python:3-slim
LABEL maintainer="hq@deepspaceprogram.com"

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y gcc && \
    apt-get install -y git && \
    apt-get install -y libcurl4 && \
    apt-get install -y libpq-dev && \
    apt-get install -y libssl-dev && \
    apt-get install -y python3-dev && \
    apt-get install -y librtmp-dev && \
    apt-get install -y libcurl4-gnutls-dev && \
    apt-get install -y libcurl4-openssl-dev && \
    apt-get install -y postgresql-9.3 && \
    apt-get install -y python-psycopg2
  
ENV PROJECT_ROOT /app
WORKDIR $PROJECT_ROOT

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt --default-timeout=1000

COPY . .
CMD python manage.py runserver 0.0.0.0:8000