# Generated by Django 2.2.7 on 2019-11-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_auto_20191114_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('C', 'created'), ('O', 'ordered'), ('R', 'refunded')], default='C', max_length=1),
        ),
    ]
