# Generated by Django 2.2.7 on 2019-11-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_auto_20191115_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
