# Generated by Django 2.2.7 on 2019-11-15 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_card_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='billing_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='commerce.BillingProfile'),
        ),
    ]
