# Generated by Django 2.2.7 on 2019-11-16 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0013_auto_20191116_2127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='UserAddress',
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'UserAddress', 'verbose_name_plural': 'UserAddresses'},
        ),
        migrations.AddField(
            model_name='card',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
