# Generated by Django 2.2.7 on 2019-11-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0015_auto_20191117_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='google_place_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
