# Generated by Django 2.2.8 on 2020-01-02 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0018_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charge', to='commerce.Charge'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='charge',
            name='billing_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='commerce.BillingProfile'),
        ),
    ]
