# Generated by Django 2.2.8 on 2020-01-02 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0019_auto_20200102_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charge', to='commerce.Charge'),
        ),
    ]
