# Generated by Django 2.2.8 on 2020-01-02 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0021_auto_20200102_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='charges', to='commerce.Card'),
        ),
    ]
