# Generated by Django 2.2.8 on 2020-01-23 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0022_charge_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='commerce.Card'),
        ),
    ]
