# Generated by Django 2.2.8 on 2020-06-10 21:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0024_auto_20200128_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='google_place',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
